### ISSUE TITLE
Using m68kdasm in Capstone Engine

### ISSUE THREAD

**Issue by emoon** [kstenerud/Musashi#3]
Hi,

I'm working on adding m68k support in https://github.com/aquynh/capstone 

"Capstone disassembly/disassembler framework: Core (Arm, Arm64, Mips, PPC, Sparc, SystemZ, X86, X86_64, XCore) + bindings (Python, Java, Ocaml) http://www.capstone-engine.org"

I wonder if it's ok to use the code in m68kdasm for doing the 'low-level' bits of the implementation?

Cheers!

**Comment by kstenerud** [comment]
Sure, no problem.

**Comment by emoon** [comment]
Sweet! Thanks for the fast reply :)
