### ISSUE TITLE
Issues compiling the latest version on macOS

### ISSUE THREAD

**Issue by dirkwhoffmann** [kstenerud/Musashi#44]
Greetings, 

first of all, I want to thank you for writing this awesome m68k emulator. I am using it with great success in a new Amiga emulator called vAmiga. 

https://github.com/dirkwhoffmann/vAMIGA

To be honest, I'm not sure if I had started vAmiga at all if I hadn't found this core.

I'm developing on macOS and had no problems compiling Musashi until now. Unfortunately, I encountered problems when trying to update to the latest version (the head revision on the master branch). 

My main issue is a linker problem. Xcode refuses to build the project now (I am using Musashi inside a C++ project).

<img width="289" alt="Bildschirmfoto 2019-11-03 um 10 57 13" src="https://user-images.githubusercontent.com/12561945/68083778-48361c80-fe2d-11e9-9b63-8aabbd87ad9d.png">

While comparing the old code with the new code, I notice the following difference: The old m68kops.h contained declarations for all functions of the opcode handler: 

```
…
void m68k_op_unpk_16_rr(void);
void m68k_op_unpk_16_mm_ax7(void);
void m68k_op_unpk_16_mm_ay7(void);
void m68k_op_unpk_16_mm_axy7(void);
void m68k_op_unpk_16_mm(void);
/* Build the opcode handler table */
void m68ki_build_opcode_table(void);

extern void (*m68ki_instruction_jump_table[0x10000])(void); /* opcode handler jump table */
extern unsigned char m68ki_cycles[][0x10000];

```
The latest m68kmake doesn’t seem to create these declarations any more:

```
#ifndef M68KOPS__HEADER
#define M68KOPS__HEADER

/* ======================================================================== */
/* ============================ OPCODE HANDLERS =========================== */
/* ======================================================================== */


/* Build the opcode handler table */
void m68ki_build_opcode_table(void);

extern void (*m68ki_instruction_jump_table[0x10000])(void); /* opcode handler jump table */
extern unsigned char m68ki_cycles[][0x10000];


/* ======================================================================== */
/* ============================== END OF FILE ============================= */
/* ======================================================================== */

#endif /* M68KOPS__HEADER */
```

In addition, I stumbled across the following (minor) issues: 

1. Xcode produces warnings about uninitialised variables: 

<img width="548" alt="Bildschirmfoto 2019-11-03 um 10 49 31" src="https://user-images.githubusercontent.com/12561945/68083787-613ecd80-fe2d-11e9-8478-85e2987116cc.png">

All warnings are due to the usage of fatalerror() which terminates the execution branch (which my compiler doesn’t recognise). 

2. File m68kfpu.c

My compiler breaks here, because it doesn’t recognise the INLINE keyword (m68kcpu.h is not included in this file)

Hope this is useful!

**Comment by emoon** [comment]
What likely needs to be fixed here is to wrap the C code (in the header) inside
```
#ifdef __cplusplus
extern {
```

...

```
#ifdef __cplusplus
}
```

Also I'm not sure about `INLINE` I would guess something like this is needed as well

```
#ifndef INLINE
#define INLINE inline
#endif
```

Also another thing would be good to setup CI for this project in order to reduce breakages in the future.

**Comment by dirkwhoffmann** [comment]
> What likely needs to be fixed here is to wrap the C code (in the header) inside

Until now, I could embed Musashi in my C++ simply like this: 

```
extern "C" {
#include "m68k.h"
#include "m68kcpu.h"
}

extern "C" int interrupt_handler(int irqLevel);
```

I think Xcode is stumbling across the missing declarations of all opcode functions.

> Also I'm not sure about INLINE I would guess something like this is needed as well

Such a thing is already present in m68kconf.h

```
/* Set to your compiler's static inline keyword to enable it, or
 * set it to blank to disable it.
 * If you define INLINE in the makefile, it will override this value.
 * NOTE: not enabling inline functions will SEVERELY slow down emulation.
 */
#ifndef INLINE
#define INLINE static __inline__
#endif /* INLINE */
```

I think the issue here is that not all C files include this header any more.

**Comment by emoon** [comment]
That might be the case yes but it's I'm a bit cleaner to have the `#ifdef __cplusplus ..` inside the headers of the library so the users of doesn't need to care (and it will work for both C/C++)

**Comment by kstenerud** [comment]
Added guards here: https://github.com/kstenerud/Musashi/commit/890efa8bf73382fe77dc99e554039aba3a764678

Give it a try and see if that helps.

**Comment by dirkwhoffmann** [comment]
No, it doesn’t help. It doesn’t change what my compiler sees, because all my Musashi includes are wrapped manually with „extern „C“. Of course, Daniel is right that the extern „C“ stuff should be inside the header files, so the user doesn’t have to care.

My linker problem is pretty strange. E.g., look at this: 

```
Undefined symbols for architecture x86_64:
  "_OPER_A7_PD_8", referenced from:
      _m68k_op_abcd_8_mm_ay7 in m68kops.o
      _m68k_op_abcd_8_mm_axy7 in m68kops.o
      _m68k_op_add_8_er_pd7 in m68kops.o
      _m68k_op_addx_8_mm_ay7 in m68kops.o
      _m68k_op_addx_8_mm_axy7 in m68kops.o
      _m68k_op_and_8_er_pd7 in m68kops.o
      _m68k_op_btst_8_r_pd7 in m68kops.o
      ...
```

But _OPER_A7_PD_8 is an inline function:

`INLINE uint OPER_A7_PD_8(void)  {uint ea = EA_A7_PD_8();  return m68ki_read_8(ea); }`

Yet I don’t understand why the linker expects this function to exist. Maybe INLINE is defined differently in various places? Just a guess…

**Comment by emoon** [comment]
I think `_m68k_op_abcd_8_mm_ay7` are generated right? Do you run the code generation?

**Comment by dirkwhoffmann** [comment]
> I think _m68k_op_abcd_8_mm_ay7, etc are generated right? 

Yes

> Do you run the code generation?

Yes, the function is right here: 

```
void m68k_op_abcd_8_mm_ay7(void)
{
	uint src = OPER_A7_PD_8();
	uint ea  = EA_AX_PD_8();
	uint dst = m68ki_read_8(ea);
	uint res = LOW_NIBBLE(src) + LOW_NIBBLE(dst) + XFLAG_AS_1();

	FLAG_V = ~res; /* Undefined V behavior */

	if(res > 9)
		res += 6;
	res += HIGH_NIBBLE(src) + HIGH_NIBBLE(dst);
	FLAG_X = FLAG_C = (res > 0x99) << 8;
	if(FLAG_C)
		res -= 0xa0;

	FLAG_V &= res; /* Undefined V behavior part II */
	FLAG_N = NFLAG_8(res); /* Undefined N behavior */

	res = MASK_OUT_ABOVE_8(res);
	FLAG_Z |= res;

	m68ki_write_8(ea, res);
}

```

The issue is that the compiler expects `_OPER_A7_PD_8` to be synthesised as a (linkable) function although it is declared inline.

**Comment by emoon** [comment]
to me it looks like `INLINE` isn't set correctly

**Comment by dirkwhoffmann** [comment]
> to me it looks like INLINE isn't set correctly

I think you're right. 

This variant produces 70 missing symbols on my machine: 

```
#ifndef INLINE
#define INLINE inline
#endif /* INLINE */
```

And this one produces 2 duplicated symbols:

```
#ifndef INLINE
#define INLINE static __inline__
#endif /* INLINE */
```

I'll investigate this further...

**Comment by emoon** [comment]
In my option just having `inline` for inline functions is the way to go unless there is some specific compelling reason to have the define.

**Comment by kstenerud** [comment]
Yes, I wrote this code 20 years ago, when inline wasn't very well standardized. It could definitely do with a few changes for the modern world...

**Comment by dirkwhoffmann** [comment]
Yet another miracle: 

```
duplicate symbol '_m68040_fpu_op1' in:
    /Users/hoff/Library/Developer/Xcode/DerivedData/vAmiga-fznzgabhmwdxunbvlovywfjbgbti/Build/Intermediates.noindex/vAmiga.build/Debug/vAmiga.build/Objects-normal/x86_64/m68kfpu.o
    /Users/hoff/Library/Developer/Xcode/DerivedData/vAmiga-fznzgabhmwdxunbvlovywfjbgbti/Build/Intermediates.noindex/vAmiga.build/Debug/vAmiga.build/Objects-normal/x86_64/m68kcpu.o
duplicate symbol '_m68040_fpu_op0' in:
    /Users/hoff/Library/Developer/Xcode/DerivedData/vAmiga-fznzgabhmwdxunbvlovywfjbgbti/Build/Intermediates.noindex/vAmiga.build/Debug/vAmiga.build/Objects-normal/x86_64/m68kfpu.o
    /Users/hoff/Library/Developer/Xcode/DerivedData/vAmiga-fznzgabhmwdxunbvlovywfjbgbti/Build/Intermediates.noindex/vAmiga.build/Debug/vAmiga.build/Objects-normal/x86_64/m68kcpu.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I checked for `m68040_fpu_op1`, but it seems to be defined solely in `m68kfpu.c`. 

Another minor issue: 

static INLINE int TEST_CONDITION(int condition)

If INLINE is set to `static __inline__`, static is repeated twice (my compiler doesn't like that 🙄).

**Comment by emoon** [comment]
just set `INLINE` to `inline`

**Comment by dirkwhoffmann** [comment]
> just set INLINE to inline

This is what I had first and what should be the right thing. This gives me the 70 missing symbols error.

**Comment by dirkwhoffmann** [comment]
In m68kcpu.h, I have noticed that OPER_A7_PD_8 (besides others) are declared twice. Is this intentional? 

```
INLINE uint OPER_A7_PD_8(void);
...
INLINE uint OPER_A7_PD_8(void)  {uint ea = EA_A7_PD_8();  return m68ki_read_8(ea); }
```

Removing the first one doesn't solve the linker problem though.

**Comment by mithrendal** [comment]
Does the linker say in which object file the symbols are missing ? Could you post the complete build log output of the linker?
I mean from my knowledge there are basically two possibilities of this error. One is that the missing symbols are not in the build e.g. no object file which does contain them. Second there are some object files, the symbols are in a object file but the other object files which use them do not declare the symbols as external. Can you upload the complete xcode project in a zip into this thread or is it too big ?

**Comment by kstenerud** [comment]
It should be set to `static inline` so that it doesn't try to make those functions publicly accessible. In theory it's supposed to imply static, but if the compiler doesn't inline it then you'll have problems.

**Comment by kstenerud** [comment]
The forward function declarations were to get around issues in the Borland compiler back in the day.

**Comment by dirkwhoffmann** [comment]
> It should be set to static inline

`static inline` does the trick. Hence, to modernise the code, INLINE could be replaced by `static inline`everywhere.

The duplicated symbols are due to this in m68kcpu.c: 

```
#include "m68kops.h"
#include "m68kcpu.h"
#include "m68kfpu.c"
```

Somebody has decided to pull in a .c file 🤭. I don't know who did this, but I think he should buy all of us a beer.

**Comment by dirkwhoffmann** [comment]
Here is a summary of the major points discussed in this thread.

Ideas to cleanup / fix  the code: 

- Add `extern „C“` inside the Musashi headers (already done by Karl)
- Remove `#include "m68kfpu.c"` from m68kcpu.c
- Add dummy assignments after calls to fatalerror() to silence the uninitialised variable warning.
- Replace `INLINE` by `static inline`

**Comment by kstenerud** [comment]
OK, bunch of fixes here: https://github.com/kstenerud/Musashi/commit/8266fbe8732daee66590a77acb3d57d9299c5426

Let me know if that works!

**Comment by dirkwhoffmann** [comment]
I had to apply two minor modifications in m68kfpu.c to make it compile without errors or warnings.

In line 4, I had to add a missing include: 

    #include "m68kcpu.h"

In line 7, I changed 

    static void fatalerror(char *format, ...)

to

    static __attribute__((noreturn)) void fatalerror(char *format, ...)

I am a little unhappy about the `__attribute__` thing, because it is a non-standard GNU extension. I don’t know if one of the newer C standards has some „official“ concept to mark a function as non-returning.

After applying the two modifications, my emulator is up and running again 😎. Many thanks for fixing Musashi so fast!

<img width="818" alt="Bildschirmfoto 2019-11-03 um 20 02 10" src="https://user-images.githubusercontent.com/12561945/68090570-7dfef380-fe75-11e9-8b11-98a4cf84f728.png">

**Comment by kstenerud** [comment]
Nice!

I've pushed those changes to the repo. I don't actually like the idea of `fatalerror()`. No emulator should kill the process with `exit()` when it encounters an illegal opcode. Fortunately it's only the FPU that's affected. Unfortunately, I'm too busy with Concise Encoding to have any cycles free to fix that atm :/
