### ISSUE TITLE
ADDA instruction with post-increment stack register operands (and possibly pre-decrement)

### ISSUE THREAD

**Issue by rlake** [kstenerud/Musashi#7]
I spent this evening creating a board simulation for the 68 Katy computer (http://www.bigmessowires.com/category/68katy/) and booting the "monitor-plus-linux-pcb.bin" uClinux image. There was an issue in the exception handling return code where the stack was off by 4 bytes versus delivery. I narrowed it down to the following instruction on the "ret_from_exception" path which appears to behave incorrectly:

    00005552: dfdf                 adda.l  (A7)+, A7

According to http://www.verycomputer.com/154_d3e3e1d2b2176a76_1.htm this case is well-defined and with a slight alteration to "m68k_op_adda_32_pi" (please excuse the hack!) I was able to boot the uClinux image successfully, i.e.

    M68KMAKE_OP(adda, 32, ., .)
    {
        uint* r_dst = &AX;

        *r_dst = MASK_OUT_ABOVE_32(*r_dst + M68KMAKE_GET_OPER_AY_32);

        if (REG_IR == 0xdfdf)
                *r_dst += 4;
    }

I expect the pre-decrement form to also be affected.

**Comment by marhel** [comment]
This issue can be closed now, I should probably have refrenced the issue in the commit, not just in PR.
